version: "3.9"

services:
  db:
    image: postgres:alpine
    container_name: sgor-postgres
    restart: always
    environment:
      - POSTGRES_USER=sgor_user
      - POSTGRES_PASSWORD=sgor_123
      - POSTGRES_DB=sgor_db
    ports:
      - "5432:5432"
    expose:
      - "5432"

  sports_items_manager:
    build: sports-item-manager-admin
    container_name: sports_items_manager
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./sports-item-manager-admin:/code
    environment:
      - DATABASE_URL=postgresql://sgor_user:sgor_123@db:5432/sgor_db


  sports_items_user:
    build: sgor_user
    container_name: sports_items_user
    restart: always
    ports:
      - "90:90"
    depends_on:
      - db
    volumes:
      - ./sgor_user:/code
    environment:
      - DATABASE_URL=postgresql://sgor_user:sgor_123@db:5432/sgor_db


# networks:
#   default:
#       name: hello_fastapi
